### ISSUE TITLE
关于防抖

### ISSUE THREAD

**Issue by ronlandzuo** [zhang-changwei/Automation-scripts-for-Aegisub#2]
某些中文字体无法支持超过1000的缩放，所以会导致字体失效，但是在进行防抖处理时并未进行提示，看能否解决这种问题，或者提供提示

**Comment by zhang-changwei** [comment]
是什么字体呢

另外这应该是字体的bug吧

**Comment by zhang-changwei** [comment]
bug来源已确定，由字体中“W”导致

**Comment by zhang-changwei** [comment]
C Font Resize脚本该问题已解决，请更新至v1.2版本，C Gradient与C Translation中该问题仍然存在，等待修复。

**Comment by zhang-changwei** [comment]
应该都修好了，去看看吧

**Comment by ronlandzuo** [comment]
怎么都只有我来issues啊！！！！另，卑鄙的我三部的ASS方便给我一套吗？我拿去调4K和做国配！25078220@qq.com万分感谢

**Comment by zhang-changwei** [comment]
可能没人敢提吧...

**Comment by yaojingzhe** [comment]
不是不敢提，是还没有研究用到这么多功能，张大神，非常感谢你开发的这插件，我才使用C Font Resize，其它还在研究怎么使用。这C Font Resize太好了，以前我的跟踪字幕都是一抖一抖地缩放，用了C Font Resize，现在是匀滑地缩放，对比了一下，你是把缩放量放大，字体缩小。这思路非常非常科学有用。非常感谢您的辛苦付出。
