### ISSUE TITLE
选中最后一行至当前行

### ISSUE THREAD

**Issue by tianziabcd** [zhang-changwei/Automation-scripts-for-Aegisub#3]
楼主，请教lua脚本：aegisub在调轴过程中，经常用到平移，目前选中当前行至最后一行，焦点在当前行的操作可以用脚本实现吗？(还可以说成是从最后一行选择到当前行)

另外通过脚本拉伸、压缩时间轴有可能实现吗？

**请直接无视下面的英文，直接详细描述你想要实现的功能，我会尽量给出回复**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zhang-changwei** [comment]
平移时间轴可以用aegisub自带的shift time>selection onward
有其他软件可以实现帧率转换，如srtedit，没有必要重复劳动

**Comment by tianziabcd** [comment]
以上提到的都是用aegisub来调整时间轴所要用到，
按住atl键平移选择行，更方便直接，自带的平移时间功能需要计算、观察、输入时间
帧率转换结合aegisub的频谱，使得时间轴调整更为方便快捷，不是单纯的转个帧率


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhang-changwei/Automation-scripts-for-Aegisub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月22日(星期五) 下午3:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhang-changwei/Automation-scripts-for-Aegisub] 选中最后一行至当前行 (Issue #3)





 
平移时间轴可以用aegisub自带的shift time&gt;selection onward
 有其他软件可以实现帧率转换，如srtedit，没有必要重复劳动
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhang-changwei** [comment]
选中了也没法整体平移的吧

**Comment by tianziabcd** [comment]
可以的，同时按住atl键移动就可以将选中的整体直接平移到目标时间，而且脚本可以设置快捷键
目前aegisub可以从当前行选取到最后一行，不过选择后焦点就变成了最后一行，若设置为不改变焦点，选择功能就失效了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhang-changwei/Automation-scripts-for-Aegisub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月22日(星期五) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhang-changwei/Automation-scripts-for-Aegisub] 选中最后一行至当前行 (Issue #3)





 
选中了也没法整体平移的吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhang-changwei** [comment]
active的只能有一行，选中了很多行设置时间轴就都跟这一行一样了

**Comment by tianziabcd** [comment]
按住alt键+鼠标平移+回车（或者设置成自动更改）
PS:看来这操作鲜为人知


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhang-changwei/Automation-scripts-for-Aegisub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月22日(星期五) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhang-changwei/Automation-scripts-for-Aegisub] 选中最后一行至当前行 (Issue #3)





 
active的只能有一行，选中了很多行设置时间轴就都跟这一行一样了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhang-changwei** [comment]
ok 我明白了 本人做特效 对对白的快捷键不是很熟。select onward这个lua可以做

**Comment by zhang-changwei** [comment]
转帧率这个无论怎么弄都不可能有动态反馈的，只能是设一个帧率看一下效果

**Comment by tianziabcd** [comment]
哦哦哦，意思选择那个有希望了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhang-changwei/Automation-scripts-for-Aegisub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月22日(星期五) 下午4:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhang-changwei/Automation-scripts-for-Aegisub] 选中最后一行至当前行 (Issue #3)





 
转帧率这个无论怎么弄都不可能有动态反馈的，只能是设一个帧率看一下效果
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhang-changwei** [comment]
你是要从当前行选中到最后一行是吧

**Comment by zhang-changwei** [comment]
而且aegisub里时间精度很低，我非常反感在aegisub里转帧率，因为aegisub里转帧率特效必炸

**Comment by tianziabcd** [comment]
另外，可以做自动在末尾加固定内容行的lua吗？
比如：
倒数第二行：由国语视界***制作
最后一行是：转载请注明出处，切勿用于商业用途
这种形式固定的内容行
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhang-changwei/Automation-scripts-for-Aegisub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月22日(星期五) 下午4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhang-changwei/Automation-scripts-for-Aegisub] 选中最后一行至当前行 (Issue #3)





 
ok 我明白了 本人做特效 对对白的快捷键不是很熟。select onward这个lua可以做
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tianziabcd** [comment]
哦哦，明白了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhang-changwei/Automation-scripts-for-Aegisub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月22日(星期五) 下午4:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhang-changwei/Automation-scripts-for-Aegisub] 选中最后一行至当前行 (Issue #3)





 
而且aegisub里时间精度很低，我非常反感在aegisub里转帧率，因为aegisub里转帧率特效必炸
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tianziabcd** [comment]
主要是焦点要在当前行，反其道而行之，选择最后一行至当前行，焦点应该就在当前行了吧


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhang-changwei/Automation-scripts-for-Aegisub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月22日(星期五) 下午4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhang-changwei/Automation-scripts-for-Aegisub] 选中最后一行至当前行 (Issue #3)





 
你是要从当前行选中到最后一行是吧
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhang-changwei** [comment]
这种你做好了每次粘过来不就行了

**Comment by tianziabcd** [comment]
好的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhang-changwei/Automation-scripts-for-Aegisub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月22日(星期五) 下午4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhang-changwei/Automation-scripts-for-Aegisub] 选中最后一行至当前行 (Issue #3)





 
这种你做好了每次粘过来不就行了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhang-changwei** [comment]
搞定了 放在了C Fast Tools > fast_selection_onward

**Comment by tianziabcd** [comment]
哇，真神速


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhang-changwei/Automation-scripts-for-Aegisub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月22日(星期五) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhang-changwei/Automation-scripts-for-Aegisub] 选中最后一行至当前行 (Issue #3)





 
搞定了 放在了C Fast Tools &gt; fast_selection_onward
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tianziabcd** [comment]
已试用，这下方便快捷多了
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhang-changwei/Automation-scripts-for-Aegisub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月22日(星期五) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhang-changwei/Automation-scripts-for-Aegisub] 选中最后一行至当前行 (Issue #3)





 
搞定了 放在了C Fast Tools &gt; fast_selection_onward
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhang-changwei** [comment]
ok

**Comment by tianziabcd** [comment]
大佬，不知可否实现用来查验ocr硬字幕是否存在漏行的情况，aegisub可以快速跳帧，查漏的话就是在已有的字幕行外可能还存在没有抓取到的字幕行，即可否实现在已知的时间轴以外(屏蔽已有的时间轴)快速跳帧？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月22日(周五) 下午5:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhang-changwei/Automation-scripts-for-Aegisub] 选中最后一行至当前行 (Issue #3)




 
ok
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhang-changwei** [comment]
啥玩意

**Comment by tianziabcd** [comment]
请问，可以增加跳转到当前行中间那一帧吗？用于查看本条时间轴是否有硬字幕存在，查看首尾的帧可以通过软件自带功能实现，但有些字幕行，就中间闪一小会儿，实样就会漏掉某些行

**Comment by zhang-changwei** [comment]
不能

**Comment by tianziabcd** [comment]
那么可否折衷一下，将时间轴均分若干份来新建空行呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月11日(星期一) 晚上8:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhang-changwei/Automation-scripts-for-Aegisub] 选中最后一行至当前行 (Issue #3)





 
不能

**Comment by zhang-changwei** [comment]
没啥意义

**Comment by tianziabcd** [comment]
请教一下，lua脚本中如何获取加载的视频的帧率呢？手册里有：

aegisub.frame_from_ms

aegisub.ms_from_frame

有没有直接获得帧率的函数或者如何间接获得帧率呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月25日(星期一) 晚上8:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhang-changwei/Automation-scripts-for-Aegisub] 选中最后一行至当前行 (Issue #3)





 
没啥意义

**Comment by zhang-changwei** [comment]
我脚本里有
```
function fpsgen()
	local f = 10000
	if aegisub.ms_from_frame(f)==nil then return 23.976 end
	local t = (aegisub.ms_from_frame(f)+aegisub.ms_from_frame(f+1))/2
	-- f = t/(1000/fps) = t/1000*fps
	local fps = f/t*1000
	return round(fps*1000)/1000
end
```

**Comment by tianziabcd** [comment]
好的，感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月28日(星期四) 下午3:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhang-changwei/Automation-scripts-for-Aegisub] 选中最后一行至当前行 (Issue #3)





 
我脚本里有
 function fpsgen() 	local f = 10000 	if aegisub.ms_from_frame(f)==nil then return 23.976 end 	local t = (aegisub.ms_from_frame(f)+aegisub.ms_from_frame(f+1))/2 	-- f = t/(1000/fps) = t/1000*fps 	local fps = f/t*1000 	return round(fps*1000)/1000 end
