### ISSUE TITLE
希望能给C Gradient加一个首尾（第一第二）行间自动时间分割，创建若干新行，萌新一行一行手动＋麻了

### ISSUE THREAD

**Issue by Hyphen-H** [zhang-changwei/Automation-scripts-for-Aegisub#5]
![2022-04-11_18-01-34](https://user-images.githubusercontent.com/103420806/162715364-0db142cb-50d0-418e-b8fb-8b0f4b587ea6.png)
就是这样相同时间间隔的字幕行。因为您的脚本运行条件就是要求有若干行存在才能运行渐变自动化，正如您发帖说的一样——
![62](https://user-images.githubusercontent.com/103420806/162715505-1cc3a3da-9773-4949-9a29-a33830174ff0.png)
那么，可以请您加入一个功能吗
让aegisub自动在首尾两行间生成时间间隔为10ms、时间连续的若干行填补首尾行的空隙，以实现更平滑以至于到最高10ms/行的渐变？

如：一开始我设置首行时间轴0:00:21.89-0:00:21.90，尾行时间轴0:00:25.30-0:00:25.31，要在这首尾两行间添加若干行
在这些行中间自动生成25310-21890=3420ms，3420ms除以10ms每行=342行
时间间隔为10ms、时间连续的字幕行，然后接下来就能更好地使用您的工具C Gradient，处理这342行，进行平滑到10ms的渐变
考虑到透明度alpha渐变仅有255级，希望您能再加入一个对于透明度，将首尾时间差平等分割时间轴为最小时间间隔（可能>10ms
）份以实现最大平滑的计算公式。。。我是编程小白，这方面只能仰仗您了555

**Comment by zhang-changwei** [comment]
首先每行时间至少为一帧，短于一帧没有任何意义

**Comment by zhang-changwei** [comment]
单行切割成逐帧已经有现成脚本，不会重复劳动

**Comment by zhang-changwei** [comment]
指路：http://unanimated.hostfree.pw/ts/scripts-manuals.htm?i=1
Hyperdimensional Relocator -> Morphing Grounds -> line2fbf

**Comment by Hyphen-H** [comment]
谢谢大佬无私帮助！是萌新多虑了！另外我想问一下您我的dependency control为什么安装不了脚本。。。
![image](https://user-images.githubusercontent.com/103420806/162856122-f3225298-9710-4d48-acc4-a0725c692057.png)
这个困扰萌新好长时间了。。。这个框框一直都是白的。。YouTube上看的教程跟着人家一步一步走，版本都一致。。他的能显示，我的显示不了。。我的aegisub换了好多版本，所有都是拉开这个条条什么都没有，请问是缺少什么东西吗，一直找不到原因。。
![image](https://user-images.githubusercontent.com/103420806/162856311-610532c5-62c5-4a73-bf83-9dd63238d595.png)

**Comment by zhang-changwei** [comment]
我没有做feed
