### ISSUE TITLE
大佬，有关C Utilities的去除sdh中的说话人功能

### ISSUE THREAD

**Issue by Hyphen-H** [zhang-changwei/Automation-scripts-for-Aegisub#6]
最近在尝试翻译一些剧，比如少正第四季和How to with john wilson S02, 这两部剧都有一个共同点就是，网上下载的webdl内封装的字幕只有sdh类型的（包含聋哑人视听指示），没有普通英文字幕，这就导致我制作字幕时为了考虑到中英文一致，必须删除所有[]或者()内的聋哑说明以及说话人，现在删除聋哑说明以及解决，现在只剩下说话人，下面表明

**Comment by Hyphen-H** [comment]
感谢大佬开发C  Utilities，烦请往下看一下萌新的问题。。

**Comment by Hyphen-H** [comment]
又遇到问题了，像这样的说话人，脚本无法一次性全部去除。。。有随机出现的说话人，其名称遵循英文人名（Xxx Xxx +随机编号，如Advertiser 1: ），有的会加以编号，如Fan 1: /Fan 2: 等等，我现在想要脚本去掉"说话人名字: "以及"说话人名字 随机编号: "的内容（注意这里冒号后面的空格也要去掉。。）烦请大佬看看哪里能改进一下哈
![2022-05-13_21-11-23](https://user-images.githubusercontent.com/103420806/168293167-6cd6a596-811b-490d-bb89-83a1dfaa4b9b.png)
![2022-05-13_21-21-47](https://user-images.githubusercontent.com/103420806/168293173-6320eb39-b3b4-4c41-b699-258bf7debeba.png)
![2022-05-13_21-21-59](https://user-images.githubusercontent.com/103420806/168293176-a111ec52-0d86-49a2-be9a-eb752c9a6fc3.png)

**Comment by zhang-changwei** [comment]
XXX: 里面有，自己找

**Comment by zhang-changwei** [comment]
这种很容易造成误删，比如文字里面本来就有冒号，用脚本请自行评估风险
